def formate_latex_table(df):
    df = df.applymap(lambda x: f'{x:.2e}' if isinstance(x, (int, float)) else x)
    latex_table = df.to_latex()
    latex_table = latex_table.replace("tabular}", "tabularx}{\\textwidth}")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("&", " & ")
    latex_table = latex_table.replace(",", " , ")
    latex_table = latex_table.replace("\\\\", " \\\\ ")
    latex_table = latex_table.replace("#", "\#")
    latex_table = latex_table.replace("llllll", "lRRRRR")
    latex_table = latex_table.replace("lllll", "lRRRR")
    latex_table = latex_table.replace("varnothing", "$\\varnothing$")
    latex_table = latex_table.replace("phantom", "\\phantom")
    latex_table = latex_table.replace(".00 ", "\phantom{.00} ")
    latex_table = latex_table.replace(".0 ", "\phantom{.0} ")

    latex_table = latex_table.replace("textbf", "\\textbf")
    latex_table = latex_table.replace("underline", "\\underline")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("runtime", "Running Time [sec]")
    latex_table = latex_table.replace("residuals", "\\ours{}")
    latex_table = latex_table.replace("permute", "Permute")
    latex_table = latex_table.replace("classic", "Classic")
    latex_table = latex_table.replace("hyperparameter", "Hyper")
    latex_table = latex_table.replace("refit_constants", "Refit")
    latex_table = latex_table.replace("post_gp", "Seeded GPLearn")

    return latex_table
