import re
def formate_latex_table_error(df):
    df = df.set_index(['rank']).drop(['equation'], axis=1)
    df = df.map(lambda x: f'{x:.2e}' if isinstance(x, (int, float)) else x)
    #df['equation'] = df['equation'].apply(lambda x: '$' + x.replace(' ', '\;') + '$')
    if 'infix' in list(df.columns):
        df['infix'] = df['infix'].apply(lambda x: '$' + re.sub(r'\s+', r';', x)  + '$') # x.replace(' ', '\;')

    latex_table = df.to_latex()
    latex_table = latex_table.replace("tabular}", "tabularx}{\\textwidth}")
    latex_table = latex_table.replace("\\end{tabularx}{\\textwidth}", "\end{tabularx}")
    latex_table = latex_table.replace(";", "\;")
    latex_table = latex_table.replace("**", "\hat{}")
    latex_table = latex_table.replace("*", "\cdot")
    latex_table = latex_table.replace("_", " ")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("&", " & ")
    latex_table = latex_table.replace(",", " , ")
    latex_table = latex_table.replace("\\\\", " \\\\ ")
    latex_table = latex_table.replace("#", "\#")
    latex_table = latex_table.replace("llllll", "lRRRRR")
    latex_table = latex_table.replace("lllll", "lRRRR")
    latex_table = latex_table.replace("varnothing", "$\\varnothing$")
    latex_table = latex_table.replace("phantom", "\\phantom")
    latex_table = latex_table.replace(".00 ", "\phantom{.00} ")
    latex_table = latex_table.replace(".0 ", "\phantom{.0} ")

    latex_table = latex_table.replace("textbf", "\\textbf")
    latex_table = latex_table.replace("underline", "\\underline")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("runtime", "Running Time [sec]")
    latex_table = latex_table.replace("width", "w")
    latex_table = latex_table.replace("viscosity", "\\eta")
    latex_table = latex_table.replace("avg vel", "v")
    latex_table = latex_table.replace("friction coef", "\\beta")
    latex_table = latex_table.replace("drop length", "d")
    latex_table = latex_table.replace("adv", "\\theta_{as}")
    latex_table = latex_table.replace("rec", "\\theta_{rs}")
    latex_table = latex_table.replace("c ", "c_")

    return latex_table

def formate_latex_constants(df):
    df = df.map(lambda x: f'{x:.2e}' if isinstance(x, (int, float)) else x)
    #df['equation'] = df['equation'].apply(lambda x: '$' + x.replace(' ', '\;') + '$')
    latex_table = df.to_latex()
    latex_table = latex_table.replace("tabular}", "tabularx}{\\textwidth}")
    latex_table = latex_table.replace("\\end{tabularx}{\\textwidth}", "\end{tabularx}")
    latex_table = latex_table.replace(";", "\;")
    latex_table = latex_table.replace("**", "\hat{}")
    latex_table = latex_table.replace("*", "\cdot")
    latex_table = latex_table.replace("_", " ")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("&", " & ")
    latex_table = latex_table.replace(",", " , ")
    latex_table = latex_table.replace("\\\\", " \\\\ ")
    latex_table = latex_table.replace("#", "\#")
    latex_table = latex_table.replace("llllll", "lRRRRR")
    latex_table = latex_table.replace("lllll", "lRRRR")
    latex_table = latex_table.replace("llll", "lRRR")
    latex_table = latex_table.replace("lll", "lRR")
    latex_table = latex_table.replace("varnothing", "$\\varnothing$")
    latex_table = latex_table.replace("phantom", "\\phantom")
    latex_table = latex_table.replace(".00 ", "\phantom{.00} ")
    latex_table = latex_table.replace(".0 ", "\phantom{.0} ")

    latex_table = latex_table.replace("textbf", "\\textbf")
    latex_table = latex_table.replace("underline", "\\underline")
    latex_table = latex_table.replace("pm", "\pm")
    latex_table = latex_table.replace("runtime", "Running Time [sec]")
    latex_table = latex_table.replace("width", "Width")
    latex_table = latex_table.replace("viscosity", "Viscosity")
    latex_table = latex_table.replace("avg vel", "AvgVel")
    latex_table = latex_table.replace("friction_coef ", "FrictionCoef")
    latex_table = latex_table.replace("drop length", "DropLength")
    latex_table = latex_table.replace("adv", "Adv")
    latex_table = latex_table.replace("rec", "Rec")

    return latex_table
